name: scrape
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser
      - name: Install all necessary packages
        run: pip install requests webdriver-manager selenium geopy chromedriver-autoinstaller pandas
    
      - name: Install ubuntu package # 우분투 관련 패키지도 설치한 후
        run: |        
          sudo apt-get install fonts-unfonts-core
          sudo apt-get install fonts-unfonts-extra
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add   
      - name: 날씨 데이터 가져오기
        env:
            NAVERMAP_API_KEY: ${{ secrets.NAVERMAP_API_KEY }}
            NAVERMAP_API_KEY_ID: ${{ secrets.NAVERMAP_API_KEY_ID }}
        run: python mini_project.py
  
      - name: 변경 사항 커밋 및 푸시
        run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions@github.com"
            git add shop_distance.csv shop_kakao.csv
            git commit -m "Update lunch menu data (auto)"
            git push
